export enum MAP_STYLE {
  My = 'mapbox://styles/heavenmei117/clurzjfa800ee01pb8qs7a187',
  Street = 'mapbox://styles/mapbox/streets-v12',
  Standard = 'mapbox://styles/mapbox/standard',
  Light = 'mapbox://styles/mapbox/light-v11',
  StepLine = 'mapbox://styles/mapbox/navigation-day-v1',
}
// top-left top-right bottom-right bottom-left
export const imgLatLngBound = [
  [120.8, 31.898],
  [122.16, 31.898],
  [122.16, 30.66],
  [120.8, 30.66],
];
export const heatImgSize: [number, number] = [4000, 4200];

const VITE_MAP_TOKEN = import.meta.env.VITE_MAPBOX_TOKEN;

export const mapTiles = {
  base: `https://api.mapbox.com/styles/v1/heavenmei117/clurxbque00v401qqfgbjar0i/tiles/256/{z}/{x}/{y}@2x?access_token=${VITE_MAP_TOKEN}`,
  roadOnly: `https://api.mapbox.com/styles/v1/billchen2k/clfdky8k2001301pi5r1wiwzu/tiles/256/{z}/{x}/{y}@2x?access_token=${VITE_MAP_TOKEN}`,
};
export const throttleTime = 100;
export const semanticArr: string[] = [
  'comfort',
  'convenience',
  'economic vitality',
  'elder friendliness',
  'livability',
  'mobility',
  'romance',
  'safety',
];

export const heatImgRootUrl: string = 'data/simap/';

export const ColorScalePalette = [
  '#f9e196',
  '#b4d8e7',
  '#b0d878',
  '#bda6cc',
  '#FDCB82',

  '#76885B',

  '#f78871',
  '#fdb38d',
  '#28cfd7',
  '#4edfc3',
  '#1a6fd9',
  '#199cd5',
  '#44b4e6',
  '#73a5e8',
  '#767edd',
  '#9b68f0',
  '#d7c1d1',
  '#aaaaaa',
  '#CA8C00',
];

export const CategoryImgRootUrl: string = 'data/category/';
export const CategoryItems: string[] = [
  'all',
  'businesses & manufacturing',
  'education',
  'food & catering',
  'government & public infrastructure',
  'healthcare',
  'life services',
  'residential',
  'retail & shopping',
  'social & entertainment',
  'sports',
  'transportation',
  'travel & attractions',
];

export const ClassImgRootUrl: string = 'data/class/';
export const ClassItems: string[] = [
  'factories and mines',
  'zone',
  'office building',
  'real estate agency',
  'company',
  'agriculture and forestry and horticulture',
  'study abroad agency',
  'news publishing',
  'stadium',
  'public toilet',
  'training institutions',
  'maintenance point',
  'pet service',
  'laundry',
  'graphic print shop',
  'photo studio',
  'funeral service',
  'logistics company',
  'post office',
  'communication business hall',
  'housekeeping',
  'lottery point of sale',
  'newsstand',
  'department store',
  'convenience store',
  'supermarket',
  'store',
  'household building materials',
  'home appliances digital',
  'housing estate',
  'market',
  'shopping center',
  'foreign institutions',
  'governments at all levels',
  'residents committee',
  'partisan groups',
  'political education institution',
  'democratic party',
  'central agency',
  'utilities',
  'administrative unit',
  'public procuratorate',
  'welfare agency',
  'social groups',
  'broadcasting',
  'dormitory',
  'chinese restaurant',
  'snack fast food restaurant',
  'foreign restaurant',
  'cake dessert shop',
  'cafe',
  'tea house',
  'subway station',
  'train station',
  'long distance bus station',
  'service area',
  'bus stop',
  'airport',
  'parking lot',
  'gas station',
  'ordinary parking space',
  'leisure square',
  'cultural palace',
  'exhibition hall',
  'church',
  'zoo',
  'farmhouse',
  'bath massage',
  'theater',
  'cinema',
  'science museum',
  'art gallery',
  'karaoke bar',
  'internet cafe',
  'game place',
  'dance hall',
  'bar',
  'apartment hotel',
  'express inn',
  'homestay',
  'ticket office',
  'star hotels',
  'resort',
  'attractions',
  'temple',
  'amusement park',
  'garden',
  'aquarium',
  'ancient artifacts',
  'botanical garden',
  'scenic area',
  'beach',
  'pharmacy',
  'medical insurance',
  'clinic',
  'nursing home',
  'medical instruments',
  'physical examination institutions',
  'general hospital',
  'specialist hospital',
  'centers for disease control and prevention',
  'emergency center',
  'library',
  'research institutions',
  'parenting education',
  'kindergarten',
  'primary school',
  'middle school',
  'adult education',
  'special education school',
  'art group',
  'colleges and universities',
  'museum',
  'gym',
];

export const MOCK_POI_COUNTER = {
  'government & public infrastructure': 96,
  healthcare: 27,
  'businesses & manufacturing': 92,
  'life services': 87,
  sports: 36,
  education: 39,
  'retail & shopping': 52,
  residential: 70,
  'travel & attractions': 46,
  transportation: 36,
  'food & catering': 47,
  'social & entertainment': 42,
};
